name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: 	ubuntu-latest
    steps:
      - name: Pring Greeting
        run: echo "Welcome Github action"
      - name: Print Bye
        run: echo "Done-Good Bye"
    
